server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://cdb-xxx.cd.tencentcdb.com:10023/passion_flare?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: daft_punk
    password: digital_love
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
files:
  path: /passion-flare/Files
